[package]
name = "trill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
rodio = "0.16.0"
glob = "0.3.0"
rand = "0.8.5"
